export const REDACTED = '[redacted]';

export const SECRET_VARIABLES = [
  'DATABASE_URL',
  'REDIS_URL',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_SESSION_TOKEN',
  'SMTP_PASSWORD',
  'SEED_MANAGER_PASSWORD',
] as const;

export const REDACT_PATHS: readonly string[] = [
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers["proxy-authorization"]',
  'req.headers["stripe-signature"]',
  'res.headers["set-cookie"]',

  'req.body.password',
  'req.body.currentPassword',
  'req.body.newPassword',
  'req.body.resetToken',
  'req.body.refreshToken',

  'password',
  'passwordHash',
  'currentPassword',
  'newPassword',
  'accessToken',
  'refreshToken',
  'refreshTokenHash',
  'resetToken',
  'tokenHash',
  'secret',
  'clientSecret',
  'apiKey',
  'cardNumber',
  'cvc',
  '*.password',
  '*.passwordHash',
  '*.currentPassword',
  '*.newPassword',
  '*.accessToken',
  '*.refreshToken',
  '*.refreshTokenHash',
  '*.tokenHash',
  '*.resetToken',
  '*.secret',
  '*.clientSecret',
  '*.cardNumber',
  '*.cvc',

  ...SECRET_VARIABLES.flatMap((name) => [name, `*.${name}`, `*.*.${name}`]),
];
